### PR TITLE
Use SQLITE_TEMP_STORE=3 on android.

### PR DESCRIPTION
**Pull request by dvc94ch**
helps sqlite figure out how to deal with temp files on android.

### CODE REVIEW

**Review by gwenn — APPROVED** [review]

**Comment by gwenn** [comment]
Not related to this PR but `Docs` check fails ! Should we specify the package: `cargo rustdoc -p rusqlite --features '...' -- -D warnings` ?

**Comment by thomcc** [comment]
Seems to be https://github.com/rust-lang/rust/issues/84162. Given that it has P-critical, I think it will get sorted.

**Comment by gwenn** [comment]
> Seems to be [rust-lang/rust#84162](https://github.com/rust-lang/rust/issues/84162). Given that it has P-critical, I think it will get sorted.

@thomcc Thanks for the investigation.

**Comment by dvc94ch** [comment]
so anything left to do other than wait?

**Comment by dvc94ch** [comment]
A release would be nice so that we can finally use rusqlite proper. We've been using our own fork because of this for 6mo, glad to see it gone soon.

**Comment by gwenn** [comment]
Ok, I will try to release `libsqlite3-sys` 0.22.1 and `rusqlite` 0.25.1 this week.

**Comment by gwenn** [comment]
Done.

**Comment by dvc94ch** [comment]
Thanks!

**Pull request merged**
