### PR TITLE
Hide IndexConstraintIter and OrderByIter

### PR DESCRIPTION
**Pull request by gwenn**
Returns `impl Iterator` directly

### CODE REVIEW

**Comment by thomcc** [comment]
Hmm, can you elaborate on why? The old code would allow someone to store the iterator somewhere. This also prevents us from implementing e.g. DoubleEndedIterator (or anything else implemented by the underlying slice iterator) without it being a breaking change.

**Comment by gwenn** [comment]
I just want to hide some implementation details.

**Comment by thomcc** [comment]
I kind of feel like we should be returning the slices from these functions anyway, e.g. 

```rust
pub fn order_bys(&self) -> &[OrderBy<'_>] { ... }
```

That avoids exposing the iterators directly and is more flexible (the user can easily turn them into an iterator).

I'm not sure if there's a reason not to do this though.

**Comment by gwenn** [comment]
You are right.

**Pull request closed without merging**
