### PR TITLE
Upgrade SQLite bundled version to 3.35.4

### PR DESCRIPTION
**Pull request by gwenn**

### CODE REVIEW

**Comment by thomcc** [comment]
Sorry I've been busy. If you're interested in cutting a release you should go for it — unfortunately I'm likely to continue to be busy for a bit, and the backlog is getting crazy. No rush though, and it's fine if you don't want to.

**Comment by gwenn** [comment]
I've already prepared the release notes but they are still some pending PRs like #908.
I am going to send a PR to update Cargo files and README anyway...

**Comment by thomcc** [comment]
Thanks. I think we probably shouldn't do #908 for now. We can do it later backwards compatibly anyway.

**Comment by gwenn** [comment]
Fine. See #930

**Pull request merged**
