### PR TITLE
Rustfmt

### PR DESCRIPTION
**Pull request by gwenn**

### CODE REVIEW

**Comment by gwenn** [comment]
Pretty sure:
https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
> To enable unstable options, set unstable_features = true in rustfmt.toml

But you may prefer to keep the default settings ?

**Comment by thomcc** [comment]
> But you may prefer to keep the default settings ?

I don't really have a strong preference. If you like these settings better they're fine.

**Comment by gwenn** [comment]
> Hm, sure. Are all of those flags stable?

I was wrong: most of this flags are unstable...

**Comment by thomcc** [comment]
Yeah... most of the useful rustfmt flags are unstable :(

That said, I still would prefer not depending on any unstable rustfmt flags. When I've worked with projects that have, it's always been a hassle to get things set up right with my editor.

**Comment by gwenn** [comment]
You are right.

**Pull request closed without merging**
