### PR TITLE
Fix compilation issues in README

### PR DESCRIPTION
**Pull request by vn971**
Without this change, the code in README doesn't compile

### CODE REVIEW

**Comment by gwenn** [comment]
README is fine (with rusqlite from master branch)...

**Comment by vn971** [comment]
@gwenn Oh, possibly some changes were made since `0.24.1` where I tested it then.. Sorry for the wrong alert if indeed smth changed in the master branch.

**Comment by gwenn** [comment]
See #830

**Comment by vn971** [comment]
Confirming, the code indeed compiles successfully if I add it to a random/new file in the `master` branch. Thanks / sorry for the wrong alert

**Pull request closed without merging**
