### PR TITLE
Bump bundled sqlite3 version to 3.36.0

### PR DESCRIPTION
**Pull request by gwenn**

### CODE REVIEW

**Comment by gwenn** [comment]
Clippy doesn't like bindgen generated tests anymore !

**Comment by gwenn** [comment]
> Clippy doesn't like bindgen generated tests anymore !

https://github.com/rust-lang/rust-bindgen/issues/2066
> Temporary use #![allow(deref_nullptr)] to suppress.

Should we apply the suggested workaround ?

**Review by thomcc — APPROVED** [review]

**Comment by thomcc** [comment]
Genuinely unsure why the tarpaulin build failed but I'd just ignore it tbh.

**Comment by gwenn** [comment]
> Genuinely unsure why the tarpaulin build failed but I'd just ignore it tbh.

Merge succeeded: https://github.com/rusqlite/rusqlite/actions/runs/983355741

**Pull request merged**
