### PR TITLE
add extra features for bundled sqlite

### PR DESCRIPTION
**Pull request by Dushistov**
This PR add some extra features that I need from bundled version.

I need fts4 feature, and because of:
> When this option is defined in the amalgamation, versions 3 and 4 of the full-text search engine is added to the build automatically
from https://www.sqlite.org/compile.html

this patch should not break any code.

### CODE REVIEW

**Review by thomcc — APPROVED** [review]
Hm, we already bundle the rest of FTS3 and FTS5 so I guess this is fine.

**Comment by gwenn** [comment]
https://sqlite.org/mark/compile.html?Because*disabled#enable_fts3_tokenizer
> Because of security concerns, the two-argument fts3_tokenizer() feature was disabled
You are sure ?

**Comment by thomcc** [comment]
Oof, nice catch!

**Review by thomcc — COMMENTED** [review]
Sorry, given the security concerns I don't think we'll take this.

I think you can still use the `LIBSQLITE3_FLAGS` env var to configure this, instead.

**Pull request closed without merging**
