### PR TITLE
Fix confusing typename used in doc for VTab and VTabCursor

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by thomcc** [comment]
I'm not an expert on rusqlite's vtable infrastructure, so @gwenn should probably be the one to review these when he has time.

**Comment by NobodyXu** [comment]
> I'm not an expert on rusqlite's vtable infrastructure, so @gwenn should probably be the one to review these when he has time.

This PR mainly fixes the document for VTab and VTabCursor.

Their doc uses the namespace ffi, however in rusqlite it is private.

So I changed to the actual path where user of this crate can actually access.

**Comment by NobodyXu** [comment]
@thomcc If you take a look at the [vtab doc](https://docs.rs/rusqlite/0.25.3/rusqlite/vtab/index.html), you will find sqlite3_vtab and sqlite3_vtab_cursor to be present in it, however the doc for VTab and VTabCursor contradicts this and used internal namespace.

**Review by thomcc — APPROVED** [review]
Oh, right. My comment was actually more about the other PRs. This is fine.

**Comment by thomcc** [comment]
Ah, actually, it should be `rusqlite::ffi::sqlite_vtab` and such. I'll fix it though.

**Comment by thomcc** [comment]
Oh, they're `pub use`d. This is fine, then.

**Pull request merged**
