### PR TITLE
Leniently parse rfc3339 timezones

### PR DESCRIPTION
**Pull request by nhynes**
https://github.com/rusqlite/rusqlite/pull/886 introduced a breaking change to databases that store RFC3339 datetimes manually without the full timezone (i.e. not strictly through this library, which includes the full timezone).  This PR relaxes the timezone requirement during parsing.

An example of when this might be problematic is when doing something like the following:
```sql
CREATE TABLE table (
  created_at  DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  -- as opposed to datetime('now'), which is not RFC3339 compliant
);
```

### CODE REVIEW

**Comment by thomcc** [comment]
> This PR relaxes the timezone requirement during parsing.

So, just to check, this is in all cases less strict than the previous code?

**Comment by nhynes** [comment]
> So, just to check, this is in all cases less strict than the previous code?

Per [chrono](https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html)

%#z | +09 | Parsing only: Same as %z but allows minutes to be missing or present.
-- | -- | --

**Review by thomcc — APPROVED** [review]
Thanks, looks good to me.

**Comment by thomcc** [comment]
Please fix the clippy and rustfmt complaints.

**Review by gwenn — APPROVED** [review]

**Pull request merged**
