### PR TITLE
Fix build failure on Debian GNU/Linux 10 (without changes of CI and clippy.toml)

### PR DESCRIPTION
**Pull request by striezel**
@thomcc:

> f you need this, I don't really see a problem with accepting the code changes (e.g. without the CI/clippy.toml/etc changes), and putting them in a 0.25.2 patch release, since they are small, unobtrusive, don't impact any public APIs, and the work has already been done.

As mentioned in #949, here's the new PR. It is essentially the same as #949, but without setting the MSRV in clippy.toml and without adding a new CI job. I'd be happy if these changes could be merged and released as a new patch release.

### CODE REVIEW

**Comment by striezel** [comment]
As expected, the clippy CI job does now warn about not using the `matches!` macro and fails for that reason. You might want to [cherry pick](https://git-scm.com/docs/git-cherry-pick) commit 2b694e8 from PR #949 to fix that. I left it out intentionally, as requested in #949.

**Comment by thomcc** [comment]
> As expected, the clippy CI job does now warn about not using the matches! macro and fails for that reason

It's fine just to allow the lint, I think.

**Comment by gwenn** [comment]
You intend to merge these changes in a dedicated branch (and not in trunk), right ?
Because I guess there will be no PR that rollbacks theses changes when rustc is upgraded in Debian.

**Comment by thomcc** [comment]
Lets take #954 instead.

**Pull request closed without merging**
